spring:
  data:
    mongodb:
      authentication-database : ${MONGO_DATABASE}
      username : ${MONGO_USERNAME}
      password : ${MONGO_PASSWORD}
      database : ${MONGO_DATABASE}
      port : ${MONGO_PORT}
      host : localhost
      
resourceServer:
  client-jwkKeyUri: ${security.oauth2.resource.jwt.key-uri} 
  client-id: ${security.oauth2.client.client-id} 
  client-secret: ${security.oauth2.client.client-secret}       
      