server:
  port: 8100
  
eureka:  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    resource:
       userInfoUri: http://localhost:8200/auth/user
        