eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: ${CLOUD_EUREKA_SERVER}

server:
  port: 5555


logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com: DEBUG  

spring:
  zipkin:
    baseUrl:  ${ZIPKIN_HOST}  
  
#zuul:
#  ignored-services: '*'
#  prefix:  /api
#  routes:
#   organizationservice: /organization/**  
#   licensingservice: /licensing/** 



