logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.springframework.context: WARN
    org.springframework.beans.factory.annotation : WARN
    com: DEBUG
    
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/eugenfazekas/Config-Repo/
          searchPaths: licensingservice,organizationservice,specialroutesservice,zuulservice
          username: native-cloud-apps
          password: 0ffended
